#
# mrzzy.co
# CI Pipeline
#

name: "CI Pipeline"
on: push
env:
  NODE_VERSION: "~20.15"
jobs:
  lint:
    name: "Lint Code"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install Node Packages
      run: npm ci --include=dev
    - name: Lint Code with 'next lint'
      run: npx next lint
    - name: Lint Code with 'standard'
      run: npx standard

  test:
    name: "Test Code"
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: Install Node Packages
      run: npm ci --include=dev
    - name: Run Tests
      run: npx jest --verbose --passWithNoTests
